repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.5.2  
    hooks:
    -   id: isort
        args: [--filter-files]
        files: \.py$
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4  # pick a git hash / tag to point to
    hooks:
    -   id: flake8      

    
